# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows\ui\res\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 548)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 250))
        MainWindow.setAcceptDrops(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setLineWidth(5)
        self.splitter.setMidLineWidth(5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groups_treeWidget = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups_treeWidget.sizePolicy().hasHeightForWidth())
        self.groups_treeWidget.setSizePolicy(sizePolicy)
        self.groups_treeWidget.setObjectName("groups_treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.groups_treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(168, 150))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parserGroupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parserGroupBox.sizePolicy().hasHeightForWidth())
        self.parserGroupBox.setSizePolicy(sizePolicy)
        self.parserGroupBox.setMinimumSize(QtCore.QSize(0, 35))
        self.parserGroupBox.setObjectName("parserGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.parserGroupBox)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.autoParserCheckBox = QtWidgets.QCheckBox(self.parserGroupBox)
        self.autoParserCheckBox.setObjectName("autoParserCheckBox")
        self.horizontalLayout.addWidget(self.autoParserCheckBox)
        self.parserComboBox = QtWidgets.QComboBox(self.parserGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parserComboBox.sizePolicy().hasHeightForWidth())
        self.parserComboBox.setSizePolicy(sizePolicy)
        self.parserComboBox.setMinimumSize(QtCore.QSize(150, 16))
        self.parserComboBox.setObjectName("parserComboBox")
        self.horizontalLayout.addWidget(self.parserComboBox)
        self.verticalLayout.addWidget(self.parserGroupBox)
        self.parserSettingsGroupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parserSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.parserSettingsGroupBox.setSizePolicy(sizePolicy)
        self.parserSettingsGroupBox.setMinimumSize(QtCore.QSize(150, 50))
        self.parserSettingsGroupBox.setObjectName("parserSettingsGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.parserSettingsGroupBox)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addWidget(self.parserSettingsGroupBox)
        self.widgetDataContent = QtWidgets.QWidget(self.widget)
        self.widgetDataContent.setMinimumSize(QtCore.QSize(300, 50))
        self.widgetDataContent.setObjectName("widgetDataContent")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetDataContent)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widgetDataContent)
        self.verticalLayout_5.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Viewer"))
        self.groups_treeWidget.headerItem().setText(0, _translate("MainWindow", "Sample"))
        __sortingEnabled = self.groups_treeWidget.isSortingEnabled()
        self.groups_treeWidget.setSortingEnabled(False)
        self.groups_treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Group1"))
        self.groups_treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Filename"))
        self.groups_treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Image"))
        self.groups_treeWidget.setSortingEnabled(__sortingEnabled)
        self.parserGroupBox.setTitle(_translate("MainWindow", "Parser"))
        self.autoParserCheckBox.setText(_translate("MainWindow", "Auto parser"))
        self.parserSettingsGroupBox.setTitle(_translate("MainWindow", "Parser Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "&Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

